version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecole_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecole_dbBis
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8889:3306"  # Maps host port 8889 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
