version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ecole_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_pass
      POSTGRES_DB: ecole_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
